language: elixir

sudo: required

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake ffmpeg libopencv-dev

elixir:
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4.1

otp_release:
  - 19.2
  - 19.0
  - 18.3
  - 18.1
  - 18.0

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
